### ISSUE TITLE
bzImage and grub.efi not found

### ISSUE THREAD

**Issue by schwannden** [schwannden/ndn-on-galileo#2]
After updating the grub repo from
`git://github.com/vathpela/grub-fedora.git`
to
`SRC_URI = "git://github.com/mjg59/grub-fedora.git"`
as suggested by
`https://communities.intel.com/thread/59949`

boot.efi and bzImage is missing after bitbake image-full-galileo

**Comment by ypchen-tw** [comment]
After giving some observation, I think the reason I got no error for changing `SRC_URI` to `git://github.com/mjg59/grub-fedora.git` without changing `SRCREV` is because `git://github.com/mjg59/grub-fedora.git` seems to be a clone of `git://github.com/vathpela/grub-fedora.git`, and the commit hash is identical, while `git://github.com/architech-backup/grub-fedora.git` is a backup only for commit `5775f32a6268dead6939d01cbe72f23972f6d3c0` of `git://github.com/vathpela/grub-fedora.git` with its own commit hash `f72d4d83931f7a6427771b480101e251a57ac1b8`. But it doesn't explain why there is no grub.efi generated when using `git://github.com/mjg59/grub-fedora.git`.

**Comment by ypchen-tw** [comment]
Interesting. A fresh build with grub repo 'git://github.com/architech-backup/grub-fedora.git' does create bzImage and grub.efi.

**Comment by schwannden** [comment]
I am so glad it magically worked......

**Comment by ypchen-tw** [comment]
Ok... Now it's interesting.

I did a a fresh build again on both 32-bit and 64-bit Debian 7.8 (VM on XenServer) with everything identical except for using `git://github.com/mjg59/grub-fedora.git`. Files were all created as expected.

I think mjg59's grub repo is identical to the original (vathpela's) one. I believe the reason that bzImage, boot.efi, and modules--3.8-r0-clanton.tgz were not created last time might still be some networking problem.

**Comment by schwannden** [comment]
Or maybe they have a line in recipe that's like

if (rand()%10 == 3) {don't build the bzImage and boot.fi;}

**Comment by ypchen-tw** [comment]
If really so, I wish I could understand the rationale behind it.
